version: '3.7'
services:
  example-api:
    image: stoplight/prism:4.6.0
    ports:
      - "3000:3000"
    volumes:
      - .:/repo-root
    entrypoint: node dist/index.js mock -p 3000 -h 0.0.0.0 /repo-root/lib/example.yml
